#!/usr/bin/env bash
printthis()
{
    echo '                                      
    $$\   $$\ $$$$$$$\   $$$$$$\  $$\   $$\ 
    $$ |  $$ |$$  __$$\ $$  __$$\ $$ |  $$ |
    $$ |  $$ |$$ |  $$ |$$ /  $$ |$$ |  $$ |
    $$ |  $$ |$$ |  $$ |$$ |  $$ |$$ |  $$ |
    \$$$$$$  |$$ |  $$ |$$$$$$$  |\$$$$$$$ |
    \______/ \__|  \__|$$  ____/  \____$$ |
                        $$ |      $$\   $$ |
                        $$ |      \$$$$$$  |
                        \__|       \______/                                        
    '
}



set -eo pipefail
IFS=$'\n\t'

helpFunction()
{
   echo ""
   echo "Usage: [./unpy check 3 del ] [ ./unpy check 2 del ] [ ./unpy check all ] [ ./unpy check 3 ] [ unpy check 2 ]"
   echo -e " ./unpy check 3 del ----> Deletes Python 3 from system"
   echo -e " ./unpy check 2 del ----> Deletes Python 2 from system"
   echo -e " ./unpy check all -----> checks all version "
   echo -e " ./unpy check 3 -----> check for version 3 "
   echo -e " ./unpy check 2 -----> check for version 3 "
   exit 1 # Exit script after printing help
}

if [ -z "$3" ];then
printthis    
fi


unpy ()
{
    case $3 in
    del)
    echo "--- Deleting files --- "
    echo "This will delete all selected python versions, select yes or no (y/n) :"
    read value
    if [ $value = y -o $value = Y ];then
        $0 $1 $2 | sudo bash -v
    elif [ $value = n -o $value = N ]; then
        echo '-- Stopping the process --'
        exit 9999
    fi
    
    ;;
    esac
} 
{
    case $2 in
        all)
        echo "---------------------------------- listing all python versions files  ------------------------------------------
        "
        echo "- below are  usr/local/bin
        "
        ls -l /usr/local/bin | grep /Library/Frameworks/Python.framework/Versions | awk '{print "rm \47/usr/local/bin/" $9 "\47"}'
        echo "- below are all x.x Versions 
        "
        ls -d /Library/Frameworks/Python.framework/Versions/* 2> /dev/null | awk '{print "rm -rf \47" $0 "\47"}'
        echo "- below are Applications under python        
        "
        ls -d /Applications/Python\ * 2> /dev/null | awk '{print "rm -rf \47" $0 "\47"}'
        ;;
        3)
        echo "---------------------------------- listing all python versions files  ------------------------------------------"
         echo "- below are  usr/local/bin   
        "
        ls -l /usr/local/bin | grep /Library/Frameworks/Python.framework/Versions/3 | awk '{print "rm \47/usr/local/bin/" $9 "\47"}'
         echo "- below are all 3.x Versions       
        "
        ls -d /Library/Frameworks/Python.framework/Versions/3.* 2> /dev/null | awk '{print "rm -rf \47" $0 "\47"}'
        echo "- below are Applications under 3.x python       
        "
        ls -d /Applications/Python\ 3.* 2> /dev/null | awk '{print "rm -rf \47" $0 "\47"}'
        ;;
        2)
        echo "---------------------------------- listing all python versions files  ------------------------------------------"
         echo "- below are  usr/local/bin     
        "
        ls -l /usr/local/bin | grep /Library/Frameworks/Python.framework/Versions/2 | awk '{print "rm \47/usr/local/bin/" $9 "\47"}'
         echo "- below are all 2.x Versions 
        "
        ls -d /Library/Frameworks/Python.framework/Versions/2.* 2> /dev/null | awk '{print "rm -rf \47" $0 "\47"}'
        echo "- below are Applications under 2.x python     
        "
        ls -d /Applications/Python\ 2.* 2> /dev/null | awk '{print "rm -rf \47" $0 "\47"}'
        ;;
        ############ testing #########
        file-x)
        ls -d /Users/ak/Desktop/Signoff/testme/lol* 2> /dev/null | awk '{print "rm -rf \47" $0 "\47"}'
    esac
}
{    
    case $1 in
        check)
        if [ -z "$2" ];
            then
                helpFunction
        fi
        ;;
        
        
    esac  

}

pushd `dirname $0` > /dev/null
    unpy $@
